#!/usr/bin/env python3
"""
Hybrid CPU/GPU Executor for GematriaScript
Analyzes programs and routes them to CPU or GPU with assembly instruction generation
"""

import struct
from typing import List, Tuple, Dict, Optional
from pathlib import Path
from enum import Enum

class ExecutionTarget(Enum):
    """Target execution platform"""
    CPU = "cpu"
    GPU = "gpu"
    HYBRID = "hybrid"

class OpcodeAnalyzer:
    """Analyzes bytecode to determine optimal execution target"""
    
    def __init__(self):
        self.gpu_friendly_ops = {0x01, 0x02, 0x03, 0x04}  # PTR_RIGHT, PTR_LEFT, INC, DEC
        self.cpu_only_ops = {0x05, 0x06, 0x07, 0x08}  # OUT, IN, LOOP_START, LOOP_END
    
    def analyze_bytecode(self, bytecode: bytes) -> Dict:
        """Analyze bytecode and determine execution target"""
        op_counts = {}
        has_io = False
        has_loops = False
        total_ops = 0
        
        for byte in bytecode:
            if byte == 0xFF:  # HALT
                continue
            op_counts[byte] = op_counts.get(byte, 0) + 1
            total_ops += 1
            
            if byte in {0x05, 0x06}:  # OUT, IN
                has_io = True
            if byte in {0x07, 0x08}:  # LOOP_START, LOOP_END
                has_loops = True
        
        # Determine execution target
        if has_io:
            # Programs with I/O must run on CPU
            target = ExecutionTarget.CPU
            reason = "Contains I/O operations"
        elif has_loops:
            # Programs with complex loops may benefit from CPU
            loop_ratio = (op_counts.get(0x07, 0) + op_counts.get(0x08, 0)) / total_ops if total_ops > 0 else 0
            if loop_ratio > 0.3:
                target = ExecutionTarget.CPU
                reason = "High loop complexity"
            else:
                target = ExecutionTarget.HYBRID
                reason = "Simple loops, can use hybrid"
        else:
            # Simple arithmetic/pointer operations - good for GPU
            gpu_ratio = sum(op_counts.get(op, 0) for op in self.gpu_friendly_ops) / total_ops if total_ops > 0 else 0
            if gpu_ratio > 0.8:
                target = ExecutionTarget.GPU
                reason = "GPU-friendly operations"
            else:
                target = ExecutionTarget.CPU
                reason = "Mixed operations"
        
        return {
            'target': target,
            'reason': reason,
            'op_counts': op_counts,
            'total_ops': total_ops,
            'has_io': has_io,
            'has_loops': has_loops
        }

class CPUAssemblyGenerator:
    """Generates x86_64 assembly instructions from GematriaScript bytecode"""
    
    def __init__(self):
        self.arch = "x86_64"
    
    def generate_assembly(self, bytecode: bytes, program_name: str = "") -> str:
        """Generate x86_64 assembly from bytecode"""
        assembly = []
        
        # Header
        assembly.append(f"; GematriaScript Assembly: {program_name}")
        assembly.append("; Generated by GematriaScript Hybrid Executor")
        assembly.append("")
        assembly.append(".section .data")
        assembly.append("tape:")
        assembly.append("    .zero 30000  ; Memory tape")
        assembly.append("")
        assembly.append(".section .text")
        assembly.append(".global _start")
        assembly.append("")
        assembly.append("_start:")
        assembly.append("    ; Initialize")
        assembly.append("    mov rdi, tape      ; Load tape address")
        assembly.append("    xor rcx, rcx       ; Pointer = 0")
        assembly.append("")
        
        # Generate instructions
        pc = 0
        loop_stack = []
        
        while pc < len(bytecode):
            op = bytecode[pc]
            
            if op == 0x01:  # PTR_RIGHT
                assembly.append(f"    ; PTR_RIGHT (pc={pc})")
                assembly.append("    inc rcx")
                assembly.append("")
            elif op == 0x02:  # PTR_LEFT
                assembly.append(f"    ; PTR_LEFT (pc={pc})")
                assembly.append("    dec rcx")
                assembly.append("")
            elif op == 0x03:  # INC
                assembly.append(f"    ; INC (pc={pc})")
                assembly.append("    inc byte [rdi + rcx]")
                assembly.append("")
            elif op == 0x04:  # DEC
                assembly.append(f"    ; DEC (pc={pc})")
                assembly.append("    dec byte [rdi + rcx]")
                assembly.append("")
            elif op == 0x05:  # OUT
                assembly.append(f"    ; OUT (pc={pc})")
                assembly.append("    movzx rax, byte [rdi + rcx]")
                assembly.append("    push rax")
                assembly.append("    call putchar")
                assembly.append("    add rsp, 8")
                assembly.append("")
            elif op == 0x06:  # IN
                assembly.append(f"    ; IN (pc={pc})")
                assembly.append("    call getchar")
                assembly.append("    mov byte [rdi + rcx], al")
                assembly.append("")
            elif op == 0x07:  # LOOP_START
                assembly.append(f"    ; LOOP_START (pc={pc})")
                label_start = f"loop_{len(loop_stack)}_start"
                label_end = f"loop_{len(loop_stack)}_end"
                loop_stack.append((label_start, label_end))
                assembly.append(f"{label_start}:")
                assembly.append("    cmp byte [rdi + rcx], 0")
                assembly.append(f"    je {label_end}")
                assembly.append("")
            elif op == 0x08:  # LOOP_END
                if loop_stack:
                    label_start, label_end = loop_stack.pop()
                    assembly.append(f"    ; LOOP_END (pc={pc})")
                    assembly.append(f"{label_end}:")
                    assembly.append("    cmp byte [rdi + rcx], 0")
                    assembly.append(f"    jne {label_start}")
                    assembly.append("")
            elif op == 0xFF:  # HALT
                assembly.append(f"    ; HALT (pc={pc})")
                assembly.append("    ; Exit program")
                assembly.append("    mov rax, 60       ; sys_exit")
                assembly.append("    xor rdi, rdi      ; exit code 0")
                assembly.append("    syscall")
                assembly.append("")
            
            pc += 1
        
        # External functions
        assembly.append("")
        assembly.append("; External functions")
        assembly.append("putchar:")
        assembly.append("    mov rdi, [rsp]")
        assembly.append("    mov rax, 1          ; sys_write")
        assembly.append("    mov rdi, 1          ; stdout")
        assembly.append("    mov rsi, rsp        ; buffer")
        assembly.append("    mov rdx, 1          ; count")
        assembly.append("    syscall")
        assembly.append("    ret")
        assembly.append("")
        assembly.append("getchar:")
        assembly.append("    mov rax, 0          ; sys_read")
        assembly.append("    mov rdi, 0          ; stdin")
        assembly.append("    mov rsi, rsp        ; buffer")
        assembly.append("    mov rdx, 1          ; count")
        assembly.append("    syscall")
        assembly.append("    mov al, [rsp]")
        assembly.append("    ret")
        
        return '\n'.join(assembly)

class GPUKernelGenerator:
    """Generates GPU kernel code from GematriaScript bytecode"""
    
    def __init__(self, use_cuda: bool = True):
        self.use_cuda = use_cuda
    
    def generate_kernel(self, bytecode: bytes, program_name: str = "") -> str:
        """Generate GPU kernel code from bytecode"""
        if self.use_cuda:
            return self.generate_cuda_kernel(bytecode, program_name)
        else:
            return self.generate_opencl_kernel(bytecode, program_name)
    
    def generate_cuda_kernel(self, bytecode: bytes, program_name: str) -> str:
        """Generate CUDA kernel"""
        kernel = []
        
        kernel.append(f"// GematriaScript GPU Kernel: {program_name}")
        kernel.append("// Generated by GematriaScript Hybrid Executor")
        kernel.append("")
        kernel.append("__global__ void gematria_kernel(")
        kernel.append("    unsigned char *bytecode,")
        kernel.append("    int bytecode_len,")
        kernel.append("    unsigned char *tape,")
        kernel.append("    int tape_size,")
        kernel.append("    int *pointer,")
        kernel.append("    unsigned char *output,")
        kernel.append("    int *output_len")
        kernel.append(") {")
        kernel.append("    int idx = blockIdx.x * blockDim.x + threadIdx.x;")
        kernel.append("    int pc = 0;")
        kernel.append("    int ptr = *pointer;")
        kernel.append("    int out_idx = 0;")
        kernel.append("    int tape_local[30000];")
        kernel.append("")
        kernel.append("    // Copy tape to local memory")
        kernel.append("    for (int i = 0; i < tape_size; i++) {")
        kernel.append("        tape_local[i] = tape[i];")
        kernel.append("    }")
        kernel.append("")
        kernel.append("    // Execute bytecode")
        kernel.append("    while (pc < bytecode_len) {")
        kernel.append("        unsigned char op = bytecode[pc];")
        kernel.append("")
        kernel.append("        switch (op) {")
        
        # Generate switch cases
        for i, byte in enumerate(bytecode):
            if byte == 0x01:
                kernel.append(f"            case 1:  // PTR_RIGHT (pc={i})")
                kernel.append("                ptr = (ptr + 1) % tape_size;")
                kernel.append("                break;")
            elif byte == 0x02:
                kernel.append(f"            case 2:  // PTR_LEFT (pc={i})")
                kernel.append("                ptr = (ptr - 1 + tape_size) % tape_size;")
                kernel.append("                break;")
            elif byte == 0x03:
                kernel.append(f"            case 3:  // INC (pc={i})")
                kernel.append("                tape_local[ptr] = (tape_local[ptr] + 1) % 256;")
                kernel.append("                break;")
            elif byte == 0x04:
                kernel.append(f"            case 4:  // DEC (pc={i})")
                kernel.append("                tape_local[ptr] = (tape_local[ptr] - 1 + 256) % 256;")
                kernel.append("                break;")
            elif byte == 0x05:
                kernel.append(f"            case 5:  // OUT (pc={i})")
                kernel.append("                if (out_idx < 10000) {")
                kernel.append("                    output[out_idx] = tape_local[ptr];")
                kernel.append("                    out_idx++;")
                kernel.append("                }")
                kernel.append("                break;")
            elif byte == 0x06:
                kernel.append(f"            case 6:  // IN (pc={i})")
                kernel.append("                tape_local[ptr] = 0;  // Skip input in GPU mode")
                kernel.append("                break;")
            elif byte == 0x07:
                kernel.append(f"            case 7:  // LOOP_START (pc={i})")
                kernel.append("                if (tape_local[ptr] == 0) {")
                kernel.append("                    int depth = 1;")
                kernel.append("                    while (depth > 0 && pc < bytecode_len) {")
                kernel.append("                        pc++;")
                kernel.append("                        if (bytecode[pc] == 7) depth++;")
                kernel.append("                        if (bytecode[pc] == 8) depth--;")
                kernel.append("                    }")
                kernel.append("                }")
                kernel.append("                break;")
            elif byte == 0x08:
                kernel.append(f"            case 8:  // LOOP_END (pc={i})")
                kernel.append("                if (tape_local[ptr] != 0) {")
                kernel.append("                    int depth = 1;")
                kernel.append("                    while (depth > 0 && pc >= 0) {")
                kernel.append("                        pc--;")
                kernel.append("                        if (bytecode[pc] == 8) depth++;")
                kernel.append("                        if (bytecode[pc] == 7) depth--;")
                kernel.append("                    }")
                kernel.append("                }")
                kernel.append("                break;")
            elif byte == 0xFF:
                kernel.append(f"            case 255:  // HALT (pc={i})")
                kernel.append("                pc = bytecode_len;")
                kernel.append("                break;")
        
        kernel.append("        }")
        kernel.append("        pc++;")
        kernel.append("    }")
        kernel.append("")
        kernel.append("    // Copy back tape")
        kernel.append("    for (int i = 0; i < tape_size; i++) {")
        kernel.append("        tape[i] = tape_local[i];")
        kernel.append("    }")
        kernel.append("")
        kernel.append("    *pointer = ptr;")
        kernel.append("    *output_len = out_idx;")
        kernel.append("}")
        
        return '\n'.join(kernel)
    
    def generate_opencl_kernel(self, bytecode: bytes, program_name: str) -> str:
        """Generate OpenCL kernel"""
        kernel = []
        
        kernel.append(f"// GematriaScript GPU Kernel: {program_name}")
        kernel.append("// Generated by GematriaScript Hybrid Executor")
        kernel.append("")
        kernel.append("__kernel void gematria_kernel(")
        kernel.append("    __global unsigned char *bytecode,")
        kernel.append("    int bytecode_len,")
        kernel.append("    __global unsigned char *tape,")
        kernel.append("    int tape_size,")
        kernel.append("    __global int *pointer,")
        kernel.append("    __global unsigned char *output,")
        kernel.append("    __global int *output_len")
        kernel.append(") {")
        kernel.append("    int idx = get_global_id(0);")
        kernel.append("    int pc = 0;")
        kernel.append("    int ptr = *pointer;")
        kernel.append("    int out_idx = 0;")
        kernel.append("    int tape_local[30000];")
        kernel.append("")
        kernel.append("    // Copy tape to local memory")
        kernel.append("    for (int i = 0; i < tape_size; i++) {")
        kernel.append("        tape_local[i] = tape[i];")
        kernel.append("    }")
        kernel.append("")
        kernel.append("    // Execute bytecode")
        kernel.append("    while (pc < bytecode_len) {")
        kernel.append("        unsigned char op = bytecode[pc];")
        kernel.append("")
        
        # Generate if-else chain
        for i, byte in enumerate(bytecode):
            if byte == 0x01:
                kernel.append(f"        if (op == 1) {{  // PTR_RIGHT (pc={i})")
                kernel.append("            ptr = (ptr + 1) % tape_size;")
                kernel.append("        }")
            elif byte == 0x02:
                kernel.append(f"        else if (op == 2) {{  // PTR_LEFT (pc={i})")
                kernel.append("            ptr = (ptr - 1 + tape_size) % tape_size;")
                kernel.append("        }")
            elif byte == 0x03:
                kernel.append(f"        else if (op == 3) {{  // INC (pc={i})")
                kernel.append("            tape_local[ptr] = (tape_local[ptr] + 1) % 256;")
                kernel.append("        }")
            elif byte == 0x04:
                kernel.append(f"        else if (op == 4) {{  // DEC (pc={i})")
                kernel.append("            tape_local[ptr] = (tape_local[ptr] - 1 + 256) % 256;")
                kernel.append("        }")
            elif byte == 0x05:
                kernel.append(f"        else if (op == 5) {{  // OUT (pc={i})")
                kernel.append("            if (out_idx < 10000) {")
                kernel.append("                output[out_idx] = tape_local[ptr];")
                kernel.append("                out_idx++;")
                kernel.append("            }")
                kernel.append("        }")
            elif byte == 0x06:
                kernel.append(f"        else if (op == 6) {{  // IN (pc={i})")
                kernel.append("            tape_local[ptr] = 0;")
                kernel.append("        }")
            elif byte == 0x07:
                kernel.append(f"        else if (op == 7) {{  // LOOP_START (pc={i})")
                kernel.append("            if (tape_local[ptr] == 0) {")
                kernel.append("                int depth = 1;")
                kernel.append("                while (depth > 0 && pc < bytecode_len) {")
                kernel.append("                    pc++;")
                kernel.append("                    if (bytecode[pc] == 7) depth++;")
                kernel.append("                    if (bytecode[pc] == 8) depth--;")
                kernel.append("                }")
                kernel.append("            }")
                kernel.append("        }")
            elif byte == 0x08:
                kernel.append(f"        else if (op == 8) {{  // LOOP_END (pc={i})")
                kernel.append("            if (tape_local[ptr] != 0) {")
                kernel.append("                int depth = 1;")
                kernel.append("                while (depth > 0 && pc >= 0) {")
                kernel.append("                    pc--;")
                kernel.append("                    if (bytecode[pc] == 8) depth++;")
                kernel.append("                    if (bytecode[pc] == 7) depth--;")
                kernel.append("                }")
                kernel.append("            }")
                kernel.append("        }")
            elif byte == 0xFF:
                kernel.append(f"        else if (op == 255) {{  // HALT (pc={i})")
                kernel.append("            pc = bytecode_len;")
                kernel.append("        }")
        
        kernel.append("        pc++;")
        kernel.append("    }")
        kernel.append("")
        kernel.append("    // Copy back tape")
        kernel.append("    for (int i = 0; i < tape_size; i++) {")
        kernel.append("        tape[i] = tape_local[i];")
        kernel.append("    }")
        kernel.append("")
        kernel.append("    *pointer = ptr;")
        kernel.append("    *output_len = out_idx;")
        kernel.append("}")
        
        return '\n'.join(kernel)

class HybridExecutor:
    """Hybrid CPU/GPU executor with assembly generation"""
    
    def __init__(self, use_cuda: bool = True):
        self.analyzer = OpcodeAnalyzer()
        self.cpu_gen = CPUAssemblyGenerator()
        self.gpu_gen = GPUKernelGenerator(use_cuda)
        self.use_cuda = use_cuda
        
        # Try to import GPU runner
        try:
            from .gematria_gpu_runner import GematriaGPUInterpreter
            self.gpu_interpreter = GematriaGPUInterpreter(use_cuda)
            self.gpu_available = True
        except ImportError:
            self.gpu_available = False
            # print("GPU runner not available, falling back to CPU")
        
        # Import CPU interpreter
        from .gematria_compiler import BytecodeInterpreter
        self.cpu_interpreter = BytecodeInterpreter()
    
    def execute_program(self, bytecode: bytes, program_name: str = "") -> Dict:
        """Execute a program on the optimal target"""
        # Analyze bytecode
        analysis = self.analyzer.analyze_bytecode(bytecode)
        target = analysis['target']
        
        result = {
            'program': program_name,
            'target': target.value,
            'reason': analysis['reason'],
            'assembly': '',
            'output': '',
            'output_length': 0,
            'success': True
        }
        
        # Generate assembly based on target
        if target == ExecutionTarget.CPU or target == ExecutionTarget.HYBRID:
            result['assembly'] = self.cpu_gen.generate_assembly(bytecode, program_name)
        
        if target == ExecutionTarget.GPU or target == ExecutionTarget.HYBRID:
            if self.use_cuda:
                result['gpu_kernel'] = self.gpu_gen.generate_cuda_kernel(bytecode, program_name)
            else:
                result['gpu_kernel'] = self.gpu_gen.generate_opencl_kernel(bytecode, program_name)
        
        # Execute on appropriate target
        try:
            if target == ExecutionTarget.GPU and self.gpu_available:
                # Execute on GPU
                output, output_len = self.gpu_interpreter.run_bytecode(bytecode)
                result['output'] = output
                result['output_length'] = output_len
            else:
                # Execute on CPU
                from .gematria_compiler import BytecodeInterpreter
                interpreter = BytecodeInterpreter()
                interpreter.load_bytecode(bytecode)
                output = interpreter.run(interactive=False)
                result['output'] = ''.join(output)
                result['output_length'] = len(output)
        except Exception as e:
            result['output'] = f"Error: {str(e)}"
            result['output_length'] = 0
            result['success'] = False
        
        return result

# Import BytecodeCompiler for compatibility
from .gematria_compiler import BytecodeCompiler
